module.exports = function getTemplate() {
	return	'<option value="160x600.relational.text.and.image.module.angled.passes.component">Relational Text And Image Module - Angled Passes Component</option>'+
			'<option value="160x600.relational.text.and.image.module.combo.tickets.portrait.component">Relational Text And Image Module - Combo Tickets Portrait Component</option>'+
			'<option value="160x600.relational.text.and.image.module.image.area.component">Relational Text And Image Module - Image Area Component</option>'+
			'<option value="160x600.relational.text.and.image.module.key.art.component">Relational Text And Image Module - Key Art Component</option>'+
			'<option value="160x600.relational.text.and.image.module.ticket.component">Relational Text And Image Module - Ticket Component</option>'+
			'<option value="160x600.relational.text.and.image.module.ticket.reel.component">Relational Text And Image Module - Ticket Reel Component</option>'+
			'<option value="160x600.relational.text.and.image.module.ticket.reel.with.countdown.component">Relational Text And Image Module - Ticket Reel With Countdown Component</option>'+
			'<option value="160x600.text.and.image.module.combo.tickets.portrait.component">Text And Image Module - Combo Tickets Portrait Component</option>'+
			'<option value="160x600.text.and.image.module.image.area.component">Text And Image Module - Image Area Component</option>'+
			'<option value="160x600.text.and.image.module.key.art.component">Text And Image Module - Key Art Component</option>'+
			'<option value="160x600.text.and.image.module.ticket.component">Text And Image Module - Ticket Component</option>'+
			'<option value="160x600.text.and.image.module.ticket.reel.component">Text And Image Module - Ticket Reel Component</option>'+
			'<option value="160x600.text.and.image.module.ticket.reel.with.countdown.component">Text And Image Module - Ticket Reel With Countdown Component</option>'+
			'<option value="160x600.text.heavy.a.module.angled.pass.and.ticket.component">Text Heavy A Module - Angled Pass And Ticket Component</option>'+
			'<option value="160x600.text.heavy.a.module.angled.passes.component">Text Heavy A Module - Angled Passes Component</option>'+
			'<option value="160x600.text.heavy.a.module.image.area.component">Text Heavy A Module - Image Area Component</option>'+
			'<option value="160x600.text.heavy.a.module.ticket.component">Text Heavy A Module - Ticket Component</option>'+
			'<option value="160x600.text.heavy.a.module.ticket.reel.component">Text Heavy A Module - Ticket Reel Component</option>'+
			'<option value="160x600.text.heavy.b.module.image.area.component">Text Heavy B Module - Image Area Component</option>'+
			'<option value="160x600.text.heavy.b.module.ticket.component">Text Heavy B Module - Ticket Component</option>'+
			'<option value="160x600.text.heavy.b.module.ticket.reel.component">Text Heavy B Module - Ticket Reel Component</option>'+
			'<option value="160x600.text.only.module.text.with.bullet.points.and.cta.button.component">Text Only Module - Text With Bullet Points And CTA Button Component</option>';
}