module.exports = function getTemplate() {
	return	'<option value="300x250.combo.relational.text.image.b.module.combo.unpacked.component">Combo Relational Text Image B Module - Combo Unpacked Component</option>'+
			'<option value="300x250.combo.relational.text.image.b.module.image.area.component">Combo Relational Text Image B Module - Image Area Component</option>'+
			'<option value="300x250.relational.text.and.image.module.image.area.component">Relational Text And Image Module - Image Area Component</option>'+
			'<option value="300x250.relational.text.and.image.module.reel.with.countdown.component">Relational Text And Image Module - Reel With Countdown Component</option>'+
			'<option value="300x250.relational.text.and.image.module.ticket.reel.component">Relational Text And Image Module - Ticket Reel Component</option>'+
			'<option value="300x250.text.and.image.module.image.area.component">Text And Image Module - Image Area Component</option>'+
			'<option value="300x250.text.and.image.module.key.art.component">Text And Image Module - Key Art Component</option>'+
			'<option value="300x250.text.and.image.module.reel.with.countdown.component">Text And Image Module - Reel With Countdown Component</option>'+
			'<option value="300x250.text.and.image.module.ticket.component">Text And Image Module - Ticket Component</option>'+
			'<option value="300x250.text.and.image.module.ticket.reel.component">Text And Image Module - Ticket Reel Component</option>'+
			'<option value="300x250.text.heavy.a.module.2.passes.c.component">Text Heavy A Module - 2 Passes C Component</option>'+
			'<option value="300x250.text.heavy.a.module.angled.pass.component">Text Heavy A Module - Angled Pass Component</option>'+
			'<option value="300x250.text.heavy.a.module.image.area.component">Text Heavy A Module - Image Area Component</option>'+
			'<option value="300x250.text.heavy.b.module.combo.unpacked.component">Text Heavy B Module - Combo Unpacked Component</option>'+
			'<option value="300x250.text.heavy.b.module.image.area.component">Text Heavy B Module - Image Area Component</option>'+
			'<option value="300x250.text.heavy.b.module.text.countdown.cta.component">Text Heavy B Module - Text Countdown CTA Component</option>'+
			'<option value="300x250.text.heavy.b.module.ticket.reel.component">Text Heavy B Module - Ticket Reel Component</option>'+
			'<option value="300x250.text.only.module.end.frame.component">Text Only Module - End Frame Component</option>'+
			'<option value="300x250.text.only.module.text.frame.bullet.points.component">Text Only Module - Text Frame Bullet Points Component</option>';
}